import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/homepage');
  await page.getByRole('button', { name: 'Đăng Nhập/Đăng ký' }).click();
  await page.getByRole('button', { name: 'Đăng ký', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('sondxse181792@fpt.edu.vn');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Số điện thoại' }).fill('0393754564');
  await page.getByRole('textbox', { name: 'Số điện thoại' }).press('Tab');
  await page.getByRole('textbox', { name: 'Họ và tên' }).fill('Duong Xuan Son');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByLabel('Giới tính').selectOption('male');
  await page.getByRole('textbox', { name: 'Ngày sinh' }).selectOption('male');
  await page.getByRole('textbox', { name: 'Ngày sinh' }).press('Tab');
  await page.getByRole('textbox', { name: 'Ngày sinh' }).fill('2002-01-13');
  await page.getByRole('textbox', { name: 'Mật khẩu', exact: true }).click();
  await page.getByRole('textbox', { name: 'Mật khẩu', exact: true }).fill('son123');
  await page.getByRole('textbox', { name: 'Xác nhận mật khẩu' }).click();
  await page.getByRole('textbox', { name: 'Xác nhận mật khẩu' }).fill('son123');
  await page.locator('form').getByRole('button', { name: 'Đăng ký' }).click();
});